Secciones del Curso. Del 1 al 5

### EDA Proveedores, Concepto

In [1]:
import pandas as pd
pd.show_versions()

d:\Anaconda\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.26100
machine             : AMD64
processor           : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : es_ES.cp1252

pandas              : 2.1.2
numpy               : 1.25.2
pytz                : 2022.7
dateutil            : 2.8.2
setuptools          : 65.6.3
pip                 : 24.0
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 5.1.0
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.1
sqlalchemy          : 2.0.23
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

In [3]:
# Usando raw string (recomendado en Windows)
tabla = pd.read_csv(r"C:\Users\rfigu\Documents\Learn\CARRERA_DATOS\Pandas_de1.5horas\BasesEjemplo\TablaEjemplo.csv" ## VentasPorProveedor.csv"
                    , sep=",")
                    #,skiprows=5)
tabla.head()

  Nombre  Edad       País Automovil
0   Juan    35     México        No
1  Pedro    41     España        Si
2  María    28       Perú        Si
3  Laura    66  Argentina        No

In [4]:
##leer una serie especifica, siempre y cuando no tenga espacio em el nombre
tabla.Edad

0    35
1    41
2    28
3    66
Name: Edad, dtype: int64

In [5]:
## leer varias serie a la vez se utiliza 2 corchetes
tabla[['Edad','País']]

   Edad       País
0    35     México
1    41     España
2    28       Perú
3    66  Argentina

In [6]:
# al invocar una serie, te detalla el tipo de objeto
tabla['Nombre']

0     Juan
1    Pedro
2    María
3    Laura
Name: Nombre, dtype: object

In [7]:
# Type me indica que tipo 
#  cuando tomo 1 columnas me devuel SERIE
type(tabla.Edad)

pandas.core.series.Series

In [8]:
# Si tomo 2 ya se convierte en DataFrame
type(tabla[['Edad','País']])

pandas.core.frame.DataFrame

In [10]:
VentasPorProveedor = pd.read_csv(r"C:\Users\rfigu\Documents\Learn\CARRERA_DATOS\Pandas_de1.5horas\BasesEjemplo\VentasPorProveedor.csv" ## TablaEjemplo.csv"
                    , sep=";"
                    ,skiprows=5)
VentasPorProveedor.head() ## Sirve para visualizar las 1ras 5 lineas de tu DataFrame

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
0,1/1/2016,Steve Ashton,Norte,Medias Femeninas,Vestimenta,6,"18,00"
1,1/1/2016,Trevor Snodgrass,Oeste,Chocolate,Comestibles,8,"3,84"
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,"6,30"
3,1/1/2016,Desmond Delaney,Sur,Sánguche de Queso,Comestibles,9,"14,40"
4,1/1/2016,Desmond Delaney,Este,Chocolate,Comestibles,14,"6,72"

In [11]:
## el resumen de tu datadrame, tipo datos, nro de filas y nulos
VentasPorProveedor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Fecha      460 non-null    object
 1   Vendedor   460 non-null    object
 2   Región     460 non-null    object
 3   Artículo   460 non-null    object
 4   Categoría  460 non-null    object
 5   Unidades   460 non-null    int64
 6   Ganancia   460 non-null    object
dtypes: int64(1), object(6)
memory usage: 25.3+ KB

VALUE_COUNT. Devuelve un objeto de tipo serie y los ordena de forma descendente

In [14]:
VentasPorProveedor.Vendedor.value_counts()

Vendedor
Sarah Bond          86
Steve Ashton        84
Desmond Delaney     76
Trevor Snodgrass    75
Dustin Gee          70
Boris Stanford      69
Name: count, dtype: int64

In [21]:
VentasPorProveedor.sort_values(by=['Vendedor','Ganancia'])

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
93,6/1/2016,Boris Stanford,Norte,Chocolate,Comestibles,2,"0,96"
450,31/1/2016,Boris Stanford,Este,Chocolate,Comestibles,3,"1,44"
259,18/1/2016,Boris Stanford,Sur,Pepinillo,Comestibles,5,"1,50"
25,2/1/2016,Boris Stanford,Este,Pan,Comestibles,4,"1,60"
64,5/1/2016,Boris Stanford,Sur,Pan,Comestibles,4,"1,60"
...,...,...,...,...,...,...,...
231,15/1/2016,Trevor Snodgrass,Este,Gorras,Vestimenta,4,"8,40"
314,21/1/2016,Trevor Snodgrass,Oeste,Bombilla,Hogar,14,"8,40"
328,22/1/2016,Trevor Snodgrass,Oeste,Bombilla,Hogar,14,"8,40"
69,5/1/2016,Trevor Snodgrass,Norte,Calcetines,Vestimenta,4,"9,00"
238,16/1/2016,Trevor Snodgrass,Sur,Shorts,Vestimenta,2,"9,80"

Indexacion Booleana

In [ ]:
## De esta forma solo cumple si es o no es , True or False, info que no esta tan util
VentasPorProveedor.Artículo == 'Gorras'

0      False
1      False
2       True
3      False
4      False
       ...
455    False
456    False
457    False
458    False
459    False
Name: Artículo, Length: 460, dtype: bool

In [25]:
## de esta forma es bastante mas util, EJ filtro por 1 Dim

VentasPorProveedor[VentasPorProveedor.Artículo == 'Gorras']

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,"6,30"
7,1/1/2016,Steve Ashton,Oeste,Gorras,Vestimenta,2,"4,20"
38,4/1/2016,Steve Ashton,Oeste,Gorras,Vestimenta,13,"27,30"
57,4/1/2016,Dustin Gee,Este,Gorras,Vestimenta,2,"4,20"
85,6/1/2016,Sarah Bond,Norte,Gorras,Vestimenta,9,"18,90"
156,10/1/2016,Trevor Snodgrass,Norte,Gorras,Vestimenta,7,"14,70"
159,11/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,2,"4,20"
170,11/1/2016,Sarah Bond,Este,Gorras,Vestimenta,9,"18,90"
186,12/1/2016,Sarah Bond,Este,Gorras,Vestimenta,11,"23,10"
187,12/1/2016,Dustin Gee,Sur,Gorras,Vestimenta,13,"27,30"
201,14/1/2016,Desmond Delaney,Norte,Gorras,Vestimenta,5,"10,50"
231,15/1/2016,Trevor Snodgrass,Este,Gorras,Vestimenta,4,"8,40"
319,22/1/2016,Dustin Gee,Este,Gorras,Vestimenta,11,"23,10"
360,25/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,7,"14,70"
368,26/1/2016,Boris Stanford,Norte,Gorras,Vestimenta,7,"14,70"
394,27/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,14,"29,40"
396,27/1/2016,Trevor Snodgrass,Norte,Gorras,Vestimenta,3,"6,30"
414,28/1/2016,Trevor Snodgrass,Sur,Gorras,Vestimenta,8,"16,80"
420,29/1/2016,Sarah Bond,Este,Gorras,Vestimenta,13,"27,30"
426,29/1/2016,Sarah Bond,Este,Gorras,Vestimenta,7,"14,70"
440,30/1/2016,Trevor Snodgrass,Este,Gorras,Vestimenta,6,"12,60"

In [ ]:
## de esta forma es bastante mas util, EJ filtro por 1 Dim
## Obs: los indices no se reinician
VentasPorProveedor[(VentasPorProveedor.Artículo == 'Gorras') & (VentasPorProveedor.Región =='Norte')]

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
85,6/1/2016,Sarah Bond,Norte,Gorras,Vestimenta,9,"18,90"
156,10/1/2016,Trevor Snodgrass,Norte,Gorras,Vestimenta,7,"14,70"
159,11/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,2,"4,20"
201,14/1/2016,Desmond Delaney,Norte,Gorras,Vestimenta,5,"10,50"
360,25/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,7,"14,70"
368,26/1/2016,Boris Stanford,Norte,Gorras,Vestimenta,7,"14,70"
394,27/1/2016,Steve Ashton,Norte,Gorras,Vestimenta,14,"29,40"
396,27/1/2016,Trevor Snodgrass,Norte,Gorras,Vestimenta,3,"6,30"

In [29]:
VentasPorProveedor[VentasPorProveedor.Vendedor.str.contains('Trevor')]

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
1,1/1/2016,Trevor Snodgrass,Oeste,Chocolate,Comestibles,8,"3,84"
5,1/1/2016,Trevor Snodgrass,Este,Cerveza,Comestibles,15,"6,00"
8,1/1/2016,Trevor Snodgrass,Este,Pan,Comestibles,12,"4,80"
10,1/1/2016,Trevor Snodgrass,Sur,Pan,Comestibles,6,"2,40"
12,1/1/2016,Trevor Snodgrass,Sur,Shorts,Vestimenta,6,"29,40"
...,...,...,...,...,...,...,...
437,30/1/2016,Trevor Snodgrass,Este,Calcetines,Vestimenta,10,"22,50"
440,30/1/2016,Trevor Snodgrass,Este,Gorras,Vestimenta,6,"12,60"
442,31/1/2016,Trevor Snodgrass,Este,Sandalias,Vestimenta,6,"63,00"
446,31/1/2016,Trevor Snodgrass,Oeste,Sudadera,Vestimenta,2,"12,00"
459,31/1/2016,Trevor Snodgrass,Sur,Pepinillo,Comestibles,7,"2,10"